[package]
name = "tuntap"
version = "0.0.1"
description = "Linux TunTap bindings"
homepage = "https://github.com/manuels/tuntap.rs"
license = " GPL-2.0"
authors = ["Manuel Sch√∂lling <manuel.schoelling@gmx.de>"]
